name: build-lint-test

on: push

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["^3.11"]
        poetry-version: ["1.4.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: List deps and poetry version
        run: poetry show && poetry -V
      - name: lint
        run: make lint
      - name: test
        run: make test
