name: deploy_to_railway_dev_env

on:
  workflow_dispatch:
#    inputs:
#      branch_name:
#        description: 'Name of the branch to deploy to development environment'
#         What if just reference the branch?
#        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Railway CLI
        run: bash <(curl -fsSL cli.new)
      - name: deploy
        env:
          RAILWAY_PROJECT_ID: 83f255f0-ccc7-4e99-b90a-7242730dd4c3
          BRANCH_NAME: ${{ github.event.inputs.branch_name }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway run -e dev --command "railway run deploy --ref $BRANCH_NAME" --project $RAILWAY_PROJECT_ID
