name: deploy_to_railway_dev_env

on:
  workflow_dispatch:
#    inputs:
#      branch_name:
#        description: 'Name of the branch to deploy to development environment'
#         What if just reference the branch?
#        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Railway CLI
        run: bash <(curl -fsSL cli.new)
      - name: deploy
        env:
          RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
          BRANCH_NAME: ${{ github.ref_name }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway run -e development "deploy --ref $BRANCH_NAME" --project $RAILWAY_PROJECT_ID
#        run: echo "Branch name is $BRANCH_NAME"