name: deploy_branch_to_dev

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
      BRANCH_NAME: ${{ github.ref_name }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Install Railway CLI
        run: bash <(curl -fsSL cli.new)
      - name: print status
        run: railway status
      - name: print current branch
        run: echo "The current branch name is $BRANCH_NAME"
      - name: deploy current branch
        run: railway up
