name: merge_dev_and_deploy_to_prod

on:
  workflow_dispatch

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "^3.10" ]
        poetry-version: [ "1.4.1" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: List deps and poetry version
        run: poetry show && poetry -V
      - name: lint
        run: make lint
      - name: test
        run: make test
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
      BRANCH_NAME: ${{ github.ref_name }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Install Railway CLI
        run: bash <(curl -fsSL cli.new)
      - name: print status
        run: railway status
      - name: print current branch
        run: echo "The current branch name is $BRANCH_NAME"
      - name: fetch changes
        run: git fetch
      - name: merge changes from dev
        run: git merge dev
      - name: deploy current branch
        run: railway up
